#---
#jobs:
#  build:
#    docker:
#      -
#        image: "circleci/openjdk:8-jdk-stretch"
#      -
#        environment:
#          POSTGRES_DB: circle_test
#          POSTGRES_USER: root
#        image: "circleci/postgres:9.6.3-alpine"
#    steps:
#      - checkout
#      -
#        restore_cache:
#          key: "cash-money-management-{{ checksum \"pom.xml\" }}"
#
#        run: "mvn dependency:go-offline"
#      -
#        save_cache:
#          key: "cash-money-management-{{ checksum \"pom.xml\" }}"
#          paths:
#            - ~/.m2
#      -
#        run: "mvn package"
#      -
#        store_test_results:
#          path: target/surefire-reports
#      -
#        store_artifacts:
#          path: target/cash-money-management-0.0.1-SNAPSHOT.jar
#    working_directory: ~/cash-money-management
#version: 2
version: 2
jobs:
  build:

    working_directory: ~/cash-money-management

    docker:
      - image: circleci/openjdk:8-jdk-stretch
      - image: circleci/postgres:9.6.3-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
          CC_TEST_REPORTER_ID: 9de9a4fd877e0a19094b122f9424acf6a590f0a8c43f18599509d0350ffe65a5

    steps:

      - checkout

      - restore_cache:
          key: cash-money-management-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - run:
        command: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
        name: "Setup Code Climate test-reporter"

      - run:
              command: |
                mkdir /tmp/test-results
                ./cc-test-reporter before-build
                mvn test
              name: "Run tests"
      - run:
              command: "./cc-test-reporter after-build -t lcov --exit-code $?\n"
              name: "Codeclimate test coverage"

      - save_cache:
          paths:
            - ~/.m2
          key: cash-money-management-{{ checksum "pom.xml" }}

      - run: mvn package

      - store_test_results:
          path: target/surefire-reports

      - store_artifacts:
          path: target/cash-money-management-0.0.1-SNAPSHOT.jar
